### ISSUE TITLE
Plugin Nothing to show

### ISSUE THREAD

**Issue by jack24254029** [NicolaVerbeeck/flutter_local_storage_inspector#24]
![image](https://github.com/NicolaVerbeeck/flutter_local_storage_inspector/assets/13265628/f2896a30-f25a-40ad-82ff-26fd1df031e8)

pubspec.yaml
```
storage_inspector: 0.4.0
preferences_local_storage_inspector: 0.4.0
drift_local_storage_inspector: 0.6.0
```

code
```dart
final StorageServerDriver driver = StorageServerDriver(
  bundleId: 'com.example.abc',
);
final PreferencesKeyValueServer preferencesKeyValueServer = PreferencesKeyValueServer(
  await SharedPreferences.getInstance(),
  'ABC',
);
final DriftSQLDatabaseServer sqlServer = DriftSQLDatabaseServer(
  id: "1", // A 'random' id for the server, just ensure you don't use the same one in the same project
  name: "ABC", // Identification name for this database, shown in the plugin UI
  database: database, // Your drift database
);
driver.addKeyValueServer(preferencesKeyValueServer);
driver.addSQLServer(sqlServer);
await driver.start();
log('StorageServerDriver: ${driver.port.toString()}');
log('StorageServerDriver: ${driver.protocolVersion.toString()}');
ref.onDispose(() {
  driver.stop();
});
```

log
```
Debug service listening on ws://127.0.0.1:55463/SlW3zJK12dI=/ws
I/flutter (19660): Storage Inspector server running on 37391 [1a574b][paused=false][service=ws://127.0.0.1:55463/SlW3zJK12dI=/ws]
[log] StorageServerDriver: 37391
[log] StorageServerDriver: 1
```

Test configuration
```
Testing ADB
=======================================
ADB defined at path: /Users/alan.chang/Library/Android/sdk/platform-tools/adb
ADB path seems ok
Checking ADB command
Starting ADB server
Listing devices
ADB devices returns: 1 device(s)
Testing SDB
=======================================
Path to SDB not found

Testing iDevice
=======================================
iMobileDevice folder defined at path: /opt/homebrew/Cellar/libimobiledevice/1.3.0_2/bin
ideviceinfo seems ok
ERROR - iproxy file not found
idevice_id seems ok
```

I think code is correct, but plugin can't show it.

**Comment by NicolaVerbeeck** [comment]
Can you provide more details? Are you running on an actual device, emulator? Which type, ...

**Comment by jack24254029** [comment]
Mac mini Apple M2 Pro (Sonoma 14.1.1)
Google Pixel 4 (Android 13)
Android Studio Giraffe | 2022.3.1 Patch 4

If I missed something, please tell me.

Thank you

**Comment by NicolaVerbeeck** [comment]
There is an additional plugin that I developed called 'Niddler' which is very similar to this one but for network requests. If you could add this to your setup, in the plugin settings in intellij/android studio it has an option under the 'Niddler > Per Project' configuration to turn on debug logging for the plugin. Since it uses the same connection mechanism, this could help us identify why this plugin is not working.

Does that sound feasible? https://pub.dev/packages/niddler_dart and https://plugins.jetbrains.com/plugin/10347-niddler

**Comment by jack24254029** [comment]
I got this.
![image](https://github.com/NicolaVerbeeck/flutter_local_storage_inspector/assets/13265628/06f486fa-08fb-4caf-90f2-6655189a280f)

```
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	at se.vidstige.jadb.JadbConnection.createTransport(JadbConnection.java:27)
	at se.vidstige.jadb.JadbConnection.createDeviceWatcher(JadbConnection.java:62)
	at com.chimerapps.discovery.device.debugbridge.DebugBridgeInterface.createDeviceWatcher(DebugBridgeInterface.kt:35)
	at com.chimerapps.discovery.model.connectdialog.DeviceScanner.startScanning(DeviceScanner.kt:39)
	at com.chimerapps.discovery.ui.ConnectDialog.init(ConnectDialog.kt:154)
	at com.chimerapps.discovery.ui.ConnectDialog.<init>(ConnectDialog.kt:139)
	at com.chimerapps.discovery.ui.ConnectDialog$Companion.show(ConnectDialog.kt:104)
	at com.chimerapps.discovery.ui.ConnectDialog$Companion.show$default(ConnectDialog.kt:93)
	at com.chimerapps.niddler.ui.component.NiddlerSessionWindow.showConnectDialog(NiddlerSessionWindow.kt:248)
	at com.chimerapps.niddler.ui.component.NiddlerSessionWindow.access$showConnectDialog(NiddlerSessionWindow.kt:86)
	at com.chimerapps.niddler.ui.component.NiddlerSessionWindow$setupConnectToolbar$1.invoke(NiddlerSessionWindow.kt:205)
	at com.chimerapps.niddler.ui.component.NiddlerSessionWindow$setupConnectToolbar$1.invoke(NiddlerSessionWindow.kt:204)
	at com.chimerapps.niddler.ui.actions.DisableableAction.actionPerformed(DisableableAction.kt:20)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:197)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:176)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:465)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by NicolaVerbeeck** [comment]
Hmm, that seems to be caused by a third party library to connect to adb
server. I wonder if there is some new security stuff on m* macs that
prevents creating local connections

**Comment by NicolaVerbeeck** [comment]
Did you turn on the debug logging option? Did it log anything to the IDE messages (bottom right)

**Comment by jack24254029** [comment]
I am not sure what you mean.

This image was from bottom right.
![image](https://user-images.githubusercontent.com/13265628/283748585-06f486fa-08fb-4caf-90f2-6655189a280f.png)

This is Niddler setting, do I set correct?
![image](https://github.com/NicolaVerbeeck/flutter_local_storage_inspector/assets/13265628/3de212f6-5b85-478d-a7b9-b0f4253e03e8)

**Comment by NicolaVerbeeck** [comment]
There should also be logs next to errors. 'Notifications' with the steps the plugin is taking to connect etc. At least that's what I hope

**Comment by jack24254029** [comment]
BTW When I clicked this URL in the log when project is running, It will lead me to Storage Inspector View and work fine.
```
I/flutter ( 1992): Storage Inspector server running on 42831 [439449][paused=false][service=ws://127.0.0.1:57627/txO9krHdu_s=/ws]
```

![image](https://github.com/NicolaVerbeeck/flutter_local_storage_inspector/assets/13265628/0dccc2b1-13e4-4446-95de-303c7c74317f)

**Comment by NicolaVerbeeck** [comment]
That's one of the reasons it is in there, to have a fallback using the built-in flutter service, which does not use the discovery mechanism employed by the dialog

**Comment by jack24254029** [comment]
Bottom right meas this?
![image](https://github.com/NicolaVerbeeck/flutter_local_storage_inspector/assets/13265628/6802f360-a1f9-436d-881a-efc34da3b8e9)
![image](https://github.com/NicolaVerbeeck/flutter_local_storage_inspector/assets/13265628/a3350757-4c54-4824-b3b6-ed23180f9b11)

**Comment by NicolaVerbeeck** [comment]
Yes next to the error icon

**Comment by jack24254029** [comment]
I use the New UI of Android Studio.
So you need to see Notifcations?
Like this
![image](https://github.com/NicolaVerbeeck/flutter_local_storage_inspector/assets/13265628/7b179672-5052-4bd1-8616-67edc1f47232)

**Comment by NicolaVerbeeck** [comment]
Yes that's what I meant. But it seems like not enough information is posted :(

**Comment by jack24254029** [comment]
I can click the url to open Storage Inspector now, so this issue's prority maybe is not high.

**Comment by jack24254029** [comment]
Hi, what information that I can provide to fix this?

**Comment by NicolaVerbeeck** [comment]
Are you using an m* mac?

**Comment by jack24254029** [comment]
Yes, Apple M2 Pro

**Comment by NicolaVerbeeck** [comment]
There have been reports of things not working on m* mac devices. As I don't have any of those I am very limited in the way I can debug this. From what I can tell it is a security permissions thing with local socket connections

**Comment by jack24254029** [comment]
Is it possible that fork your code and let me debug it, push a MR to you?

**Comment by NicolaVerbeeck** [comment]
Feel free to fork, these repositories are public

**Comment by jack24254029** [comment]
I think I need the code of Storage Inspector in the Jetbrains Plugin

**Comment by NicolaVerbeeck** [comment]
You mean this public repo? https://github.com/NicolaVerbeeck/local_storage_inspector_plugin All the items you need are either in my profile's repositories or in https://github.com/Chimerapps

**Comment by jack24254029** [comment]
OK. I will try to debug it. Thank you very much.

**Comment by jack24254029** [comment]
It wroked with Android Studio Jellyfish | 2023.3.1 Patch 1
